<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="canais fechados de filmes e camais abertos">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <style>
    body{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);background-size:400% 400%;animation:gradientAnimation 10s ease infinite}@keyframes gradientAnimation{0%{background-position:0 50%}50%{background-position:100% 50%}100%{background-position:0 50%}}.header{text-align:center;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);background-color:#f1f1f1;padding:20px}.header h1{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#333;font-size:24px;margin:0}.header1{text-align:center;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);background-color:#f1f1f1;padding:20px}.header1 h1{color:#ff000a;font-size:24px;margin:0}h3{color:#fff100}.link-box a{text-decoration:none}.box-container{display:flex;flex-wrap:wrap;justify-content:center;align-items:flex-start;padding:20px}.link-box{text-align:center;padding:20px;border:1px solid #ccc;border-radius:10px;max-width:400px;flex:0 0 100%;margin-bottom:20px;background-color:#fff;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);box-shadow:0 2px 4px rgba(0,0,0,0.1)}.link-box .image-container{display:flex;justify-content:center}.link-box .image-container img{border-radius:50%;max-width:100px;max-height:100px;object-fit:cover}footer{background-color:#667eea;color:#fff;text-align:center;padding:20px 0}.footer-content{font-size:14px}
  </style>
</head>
<body>
  <div class="header"><h1>LISTA DE CANAIS</h1></div><div class="header1"><h1>USEM BLOQUEADOR DE ADS PARA FACILITAR SUAS VIDAS</h1></div><div class="container"><div class="box-container"><div class="link-box"><a href="https://embedflix.net/tv/space"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSPYEx6bwaDntVYe2R5QJFxgP3CmI1cnN8fg&usqp=CAU"></div><h3>SPACE</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-action-hd"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO5PPWoXoxfnThEq6PeC47ibItb-JgC8tbqA&usqp=CAU"></div><h3>TELECINE ACTION HD</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-touch"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmO6SMjPXgNYD6K_4N5jT82JJMkTC__a5WCg&usqp=CAU"></div><h3>TELECINE TOUCH</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-cult"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBoT6PI4SajlXYBqwB-17HGjN8xv6wWQzYRQ&usqp=CAU"></div><h3>TELECINE CULT</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-fun-hd"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXmkg_ic3G7b9jRjg8GMqLj6iBal2U4Tx3LA&usqp=CAU"></div><h3>TELECINE FUN HD</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-premium-hd"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeLEr4K9D5xVTlbVMawFaZ4ZohH2kCje3wRw&usqp=CAU"></div><h3>TELECINE PREMIUM HD</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/telecine-pipoca-hd"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA8vjF7a5P48Ny9U6JHN1OROBFQWbk-k3G2A&usqp=CAU"></div><h3>TELECINE PIPOCA HD</h3></a></div><div class="link-box"><a href="https://embedflix.net/tv/record-tv-sp"><div class="image-container"><img alt="Banner"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3KBr14axsDo4pwXiXn0Nry-KVvNvFVMD_Xg&usqp=CAU"></div><h3>RECORD TV SP</h3></a></div></div></div><footer><div class="container"><div class="footer-content"><p>© 2023 VEM_BRABO. Todos os direitos não reservados.</div></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
